name: TEMA
version: 1.0
main: dev.craftwarestudios.tema.ExamplePlugin
author: xw1w1
commands:
  tema-debug:
    description: Open the GUI example
    usage: /tema-debug [shared|instance]
permissions:
  gui.example:
    default: true
