# why not paper-plugin.yml?
# ^ because we don't need it -e
name: TEMA
version: '${version}'
main: dev.tuffstudios.tema.TEMA
author: Egor Morozov
api-version: 1.21

# the fuck is this
commands:
  tema-debug:
    description: Open the GUI example
    usage: /tema-debug [shared|instance]
permissions:
  gui.example:
    default: true
