# why not paper-plugin.yml?
name: TEMA
version: '${version}'
main: dev.craftwarestudios.tema.ExamplePlugin
author: xw1w1

# the fuck is this
commands:
  gui:
    description: Open the GUI example
    usage: /gui [shared|personal]
permissions:
  gui.example:
    default: true
